name: the-experiment
favicon: null
layout_spectrum: 0.01837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7eed1'
    - '#2192b4'
    - '#8ca496'
    - '#161614'
    - '#474445'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
