name: the-experiment
favicon: null
layout_spectrum: 0.7109
typography_spectrum: 0.99183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2dddf'
    - '#010101'
    - '#8c9787'
    - '#364b42'
    - '#00718c'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
